'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,selected=null,run=null,health=null,polling=false;
const fmt=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
const badge=s=>`<span class="badge ${['completed','SUPPORTED','IMPROVED'].includes(s)?'good':['failed','REJECTED','cancelled'].includes(s)?'bad':s==='running'?'running':''}">${esc(s.replaceAll('_',' ').toLowerCase())}</span>`;
const time=d=>new Date(d).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
async function api(path,body){const res=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Veda-Token':state?.token||''},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'Request failed');return data}
function showError(e){$('error').textContent=e.message||e;$('error').hidden=false}
async function refresh(){if(polling)return;polling=true;try{state=await api('/api/state');$('error').hidden=true;renderState();if(!selected&&state.runs.length)selected=state.runs[0].id;if(selected){const data=await api(`/api/runs/${encodeURIComponent(selected)}`);run=data.run;renderRun(data)}if(state.last_error)showError(state.last_error)}catch(e){showError(e)}finally{polling=false}}
function renderState(){
 const runs=state.runs;const experiments=runs.flatMap(r=>r.experiments||[]);const best=runs.filter(r=>r.baseline).sort((a,b)=>b.improvement-a.improvement)[0];
 $('workspace-name').textContent=state.config.name;$('stat-runs').textContent=runs.length;$('stat-experiments').textContent=experiments.length;$('stat-best').textContent=best?fmt(best.improvement)+'%':'—';$('stat-best-caption').textContent=best?`${best.config.metric} · ${best.mode==='scripted-demo'?'scripted demo':'local model'} · ${best.baseline.benchmark}`:'Start with a baseline';
 $('model-name').textContent=state.config.model.replace('-Q4_K_M','');
 $('hardware-short').textContent=`${state.hardware.cpu} · ${state.hardware.memory_gb} GB unified memory`;
 $('history-count').textContent=`${runs.length} saved investigation${runs.length===1?'':'s'}`;
 $('new-run').disabled=!!state.active;$('example-run').disabled=!!state.active;
 $('recent').innerHTML=runs.length?runs.slice(0,5).map(r=>`<button class="history-row" data-run="${esc(r.id)}"><span class="history-icon">◈</span><div><strong>${esc(r.objective)}</strong><small>${time(r.created)} · ${r.experiments?.length||0} experiments · ${esc(r.mode)}</small></div>${badge(r.status)}<span>↗</span></button>`).join(''):'<div class="blank-history">No investigations yet. Your first experiment is a good place to start.</div>';
 $('memory-list').innerHTML=runs.length?runs.map(r=>`<article class="memory-card"><h3>${esc(r.objective)}</h3>${badge(r.status)}<p>${esc(r.id)} · ${esc(r.mode)} · ${fmt(r.improvement)}% best reduction</p><p>${(r.experiments||[]).map(e=>`${esc(e.hypothesis)} — ${esc(e.status)}`).join('<br>')}</p><button class="text-btn" data-run="${esc(r.id)}">Open investigation ↗</button>${r.report?`<a class="text-btn" href="/api/runs/${encodeURIComponent(r.id)}/report">Download report ↓</a>`:''}</article>`).join(''):'<div class="blank-history">Your hypotheses and results will be saved here.</div>';
 document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>{selected=b.dataset.run;switchView('lab');refresh()});
 const h=state.hardware;$('system-details').innerHTML=[['Processor',h.cpu],['Memory',`${h.memory_gb} GB`],['Model',state.config.model],['Endpoint',state.config.endpoint],['Context profile',`${h.context.toLocaleString()} tokens · one model slot`]].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');$('workspace-path').textContent=state.workspace;
}
function renderRun(data){
 const r=data.run;$('empty').hidden=true;$('run-detail').hidden=false;$('run-title').textContent=r.objective;$('run-status').outerHTML=badge(r.status).replace('<span ','<span id="run-status" ');$('run-subtitle').textContent=`${r.id} · ${time(r.created)} · Target: ${r.config.target_percent}% less ${r.config.metric}`;
 const val=m=>m?m[{'B/op':'bytes_op','allocs/op':'allocs_op','ns/op':'ns_op'}[r.config.metric]]:null;const b=val(r.baseline);const best=(r.experiments||[]).find(x=>x.id===r.best);
 $('baseline').textContent=b!==null?`${fmt(b)} ${r.config.metric}`:'Measuring…';$('best-value').textContent=best?`${fmt(val(best.measurement))} ${r.config.metric}`:'—';$('improvement').textContent=r.best?`${fmt(r.improvement)}%`:'—';
 $('experiments').innerHTML=(r.experiments||[]).map(e=>`<tr><td><strong>${esc(e.hypothesis)}</strong><small>${esc(e.id)}</small></td><td>${badge(e.status)}</td><td>${e.measurement?.tests_passed?fmt(e.improvement)+'%':'—'}</td><td><button class="inspect" data-exp="${esc(e.id)}" aria-label="Inspect ${esc(e.id)}">↗</button></td></tr>`).join('');
 $('run-progress').textContent=r.error|| (r.status==='running'?`In progress: ${r.stage}…`:r.improvement>=r.config.target_percent?'Target met. Review the patch and reproduce the result.':'Investigation finished. The target was not reached.');
 $('run-mode').textContent=r.mode==='scripted-demo'?'Scripted proposals · Real measurements':'Local model · Real measurements';$('cancel').hidden=!(state.active===r.id);$('report-link').hidden=!r.report;$('report-link').href=`/api/runs/${encodeURIComponent(r.id)}/report`;$('patch-link').hidden=!r.best||!r.report;$('patch-link').href=`/api/runs/${encodeURIComponent(r.id)}/patch`;
 $('events').innerHTML=data.events.slice(-14).reverse().map(e=>`<li><span class="event-dot"></span><div><strong>${esc(e.message)}</strong><p>${time(e.at)}</p></div></li>`).join('');
 document.querySelectorAll('[data-exp]').forEach(b=>b.onclick=()=>inspect(b.dataset.exp));
}
async function inspect(id){try{const d=await api(`/api/runs/${encodeURIComponent(selected)}/experiments/${encodeURIComponent(id)}`);$('exp-title').textContent=`${id} · ${d.experiment.status}`;$('exp-summary').textContent=`${d.experiment.hypothesis}. ${d.experiment.rationale} ${d.experiment.error||''}`;$('exp-integrity').textContent=d.verified?'✓ Evidence checksums verified':'Evidence integrity check failed';$('exp-patch').textContent=d.patch||'No valid candidate patch was produced.';$('exp-output').textContent=d.stdout+'\n'+d.stderr;$('experiment-dialog').showModal()}catch(e){showError(e)}}
async function checkHealth(){try{health=await api('/api/health');$('connection').textContent=health.docker&&health.model_ready?'Local system ready':'Setup needs attention';$('health-details').innerHTML=`<div class="health-row">Docker sandbox ${badge(health.docker?'completed':'unavailable')}</div><p class="muted">${esc(health.docker?'Pinned image available. Experiments run offline.':health.docker_error)}</p><div class="health-row">Local model ${badge(health.model_ready?'completed':'unavailable')}</div><p class="muted">${esc(health.model_ready?'Local inference endpoint is responding.':health.model_error)}</p>`}catch(e){showError(e)}}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==view+'-view');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='system')checkHealth()}
function openForm(){if(!state)return;$('form-error').hidden=true;$('benchmark').value=state.config.benchmark==='Benchmark'?'^BenchmarkRender$':state.config.benchmark;$('target').value=state.config.target_percent;$('metric').value=state.config.metric;$('new-dialog').showModal()}
$('new-run').onclick=openForm;$('example-run').onclick=openForm;
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('refresh').onclick=()=>{refresh();checkHealth()};
$('run-form').onsubmit=async e=>{e.preventDefault();$('start-button').disabled=true;$('form-error').hidden=true;try{const d=await api('/api/runs',{objective:$('objective').value,benchmark:$('benchmark').value,metric:$('metric').value,target:Number($('target').value),max_experiments:Number($('budget').value),demo:$('mode').value==='demo'});selected=d.id;$('new-dialog').close();$('error').hidden=true;setTimeout(refresh,250)}catch(e){$('form-error').textContent=e.message;$('form-error').hidden=false}finally{$('start-button').disabled=false}};
$('cancel').onclick=async()=>{try{await api('/api/cancel',{});await refresh()}catch(e){showError(e)}};
refresh();checkHealth();setInterval(refresh,2500);
