'use strict';
const $=id=>document.getElementById(id);
let library={investigations:[]}, selected='', current=null, view='agents', tab='agents', selectedExperiment='', cy=null, experimentCy=null, graphKey='', experimentKey='', networkLayout=true, busy=false, refreshing=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=value=>String(value||'').slice(0,10);
const time=value=>value?new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
const badge=status=>`<span class="badge ${esc(String(status).toLowerCase())}">${esc(status)}</span>`;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,7000)}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Veda-Token':library.token||'',...options.headers}});if(!response.ok){const body=await response.json().catch(()=>({error:'Request failed'}));throw new Error(body.error||`HTTP ${response.status}`)}return response.json()}
function switchView(next){view=next;$('welcome').hidden=next!=='composer';$('composer').hidden=next!=='composer';$('workspace').hidden=next!=='workspace';$('library').hidden=next!=='library';$('agent-dashboard').hidden=next!=='agents';$('agents-button').classList.toggle('active',next==='agents');$('page-label').textContent=next==='library'?'Knowledge library':next==='workspace'?'Investigation':next==='agents'?'Agent dashboard':'Repository intelligence';if(next==='library')renderLibrary();if(next==='agents')renderAgentDashboard();if(next==='workspace')showTab(tab)}
function newInvestigation(){selected='';current=null;location.hash='new';switchView('composer');renderSidebar();$('repo-url').focus()}
function showTab(name){tab=name;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!=='tab-'+name);if(name==='agents')renderCrew();if(name==='architecture')requestAnimationFrame(drawArchitecture);if(name==='experiments')requestAnimationFrame(drawExperiments)}
async function selectRun(id){selected=id;current=null;tab='agents';resetCrewSelection();location.hash=encodeURIComponent(id);graphKey='';experimentKey='';selectedExperiment='';switchView('workspace');renderSidebar();try{const run=await api('/api/investigations/'+encodeURIComponent(id));if(selected===id){current=run;renderRun()}}catch(error){toast(error.message)}}
function renderSidebar(){const rows=library.investigations||[];$('run-count').textContent=rows.length;$('library-count').textContent=library.revisions||0;$('investigation-list').innerHTML=rows.length?rows.map(r=>`<button class="run-item ${r.id===selected?'active':''}" data-run="${esc(r.id)}"><strong>${esc(r.repository||r.url.replace('https://github.com/',''))}</strong><small>${esc(r.stage)} · ${esc(time(r.created))}${r.reused_from?' · reused':''}</small></button>`).join(''):'<div class="empty-note">Your investigations will appear here.</div>';$('investigation-list').querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>selectRun(b.dataset.run));$('agents-live-count').textContent=rows.filter(r=>r.status==='running').length;$('model-label').textContent=library.model||'Local model';$('start-button').disabled=!!library.active||busy;$('connection-status').textContent=library.active?'Investigation in progress':'Connected · Local workspace'}
function renderLibrary(){const rows=library.investigations||[];$('library-stats').innerHTML=[[library.repositories||0,'Repositories'],[library.revisions||0,'Exact revisions'],[rows.length,'Investigations'],[library.reused||0,'Evidence reuses']].map(([value,label])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('');$('knowledge-location').textContent='Shared storage: '+(library.knowledge_dir||'Loading…');$('library-table').innerHTML=rows.length?`<table><thead><tr><th>REPOSITORY</th><th>REVISION</th><th>OBJECTIVE</th><th>STATUS</th><th>RECORDED</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="source-button" data-run="${esc(r.id)}">${esc(r.repository||r.url)}</button></td><td><code>${esc(short(r.commit)||'Resolving')}</code></td><td>${esc(r.objective)}</td><td>${badge(r.status)}</td><td>${esc(time(r.created))}${r.reused_from?' · reused':''}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">No saved knowledge yet. Start an investigation to build your library.</p>';$('library-table').querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>selectRun(b.dataset.run))}
function sourceButtons(root){root.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>showSource(b.dataset.source,Number(b.dataset.line)||1))}
function renderRun(){const r=current;if(!r)return;$('repo-name').textContent=r.repository.name||r.request.url;$('run-objective').textContent=r.request.objective;$('run-status').className='badge '+r.status;$('run-status').textContent=r.status;$('run-revision').textContent=r.repository.commit?'commit '+short(r.repository.commit):'Resolving revision';$('run-time').textContent=time(r.created);$('stage-label').textContent=r.stage;$('cancel-button').hidden=r.status!=='running';$('rerun-button').disabled=!!library.active;$('download-report').href='/api/investigations/'+encodeURIComponent(r.id)+'/report';$('download-evidence').href='/api/investigations/'+encodeURIComponent(r.id)+'/evidence';$('reuse-banner').hidden=!r.reused_from;$('reuse-banner').textContent=`Matching knowledge reused from ${r.reused_from||''}. Original evidence recorded ${time(r.evidence_created)}; this is not a fresh runtime measurement.`;
 const graph=r.architecture||{},experiments=r.experiments||[];$('stat-files').textContent=(r.repository.files||[]).length;$('stat-components').textContent=(graph.nodes||[]).length;$('stat-experiments').textContent=experiments.length;$('stat-findings').textContent=(r.findings||[]).length;
 $('activity').innerHTML=(r.events||[]).map(e=>`<div class="activity-item">${esc(e.message)}<small>${esc(time(e.at))}</small></div>`).join('')||'<p class="muted">Waiting for investigation to begin…</p>';
 $('summary').textContent=r.summary|| (r.status==='running'?'Veda is gathering evidence. The report and graphs update as each stage finishes.':'Observed checks are available in Experiments. No local-model summary was produced.');
 $('findings').innerHTML=(r.findings||[]).map(f=>`<div class="finding">${badge(f.severity)}<strong>${esc(f.title)}</strong><p>${esc(f.evidence)}</p><button class="source-button" data-source="${esc(f.path)}" data-line="${f.line}">${esc(f.path)}:${f.line}</button><p class="muted">${esc(f.basis)}</p></div>`).join('');sourceButtons($('findings'));
 const limits=[...(r.limits||[])];if(r.error)limits.unshift(r.error);if(!limits.length)limits.push('No additional coverage limits reported. Passing checks do not prove the absence of defects.');$('limits').innerHTML=limits.map(x=>`<li>${esc(x)}</li>`).join('');renderReport(r.report);
 const details=[['Repository',r.repository.name||r.request.url],['Exact revision',r.repository.commit||'Resolving'],['Analyzer',r.analyzer],['Evidence signature',r.signature||'Preparing'],['Matching prior runs',r.prior_knowledge||0],['Evidence origin',r.reused_from?`${r.reused_from} · ${time(r.evidence_created)}`:'Fresh investigation'],['Storage',library.knowledge_dir||'']];$('knowledge-detail').innerHTML=details.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');
 if(tab==='agents')renderCrew();if(tab==='architecture')drawArchitecture();if(tab==='experiments')drawExperiments();}
function renderReport(text){const root=$('report-content');root.replaceChildren();if(!text){const p=document.createElement('p');p.textContent='The report is being prepared. Completed steps are already available under Experiments.';root.append(p);return}for(const line of text.split('\n')){if(!line.trim())continue;let el;if(line.startsWith('### ')){el=document.createElement('h3');el.textContent=line.slice(4)}else if(line.startsWith('## ')){el=document.createElement('h2');el.textContent=line.slice(3)}else if(line.startsWith('# ')){el=document.createElement('h1');el.textContent=line.slice(2)}else{el=document.createElement('p');el.textContent=line.replaceAll('**','').replaceAll('`','')}root.append(el)}}
const colors={repository:'#254f45',terraform:'#8980bc',module:'#aaa2cf',variable:'#c3bed8',container:'#79a7ba',image:'#a2c2ce',dockerfile:'#91adba',component:'#719a73',network:'#c4a566',volume:'#c4a566',kubernetes:'#8ba2c5'};
function graphStyle(){return[{selector:'node',style:{'shape':'round-rectangle','width':145,'height':58,'background-color':'data(color)','border-width':1,'border-color':'#ffffff','label':'data(label)','font-size':10,'font-family':'-apple-system, sans-serif','color':'#ffffff','text-valign':'center','text-wrap':'wrap','text-max-width':125}},{selector:'edge',style:{'width':1.3,'line-color':'#a4b4aa','target-arrow-color':'#a4b4aa','target-arrow-shape':'triangle','curve-style':'bezier','label':'data(label)','font-size':8,'text-background-color':'#fbfcfa','text-background-opacity':.95,'text-background-padding':3,'color':'#748579','text-rotation':'autorotate'}},{selector:':selected',style:{'border-width':3,'border-color':'#d7dfad'}},{selector:'.faded',style:{'opacity':.15}},{selector:'.highlight',style:{'border-width':4,'border-color':'#d0b044'}}]}
function drawArchitecture(){if(!current||view!=='workspace'||tab!=='architecture')return;const graph=current.architecture||{nodes:[],edges:[]};const key=current.id+JSON.stringify(graph);if(key===graphKey&&cy){cy.resize();return}graphKey=key;if(cy)cy.destroy();const elements=[...(graph.nodes||[]).map(n=>({data:{...n,color:colors[n.kind]||'#859b8f',label:n.label.length>50?n.label.slice(0,47)+'…':n.label}})),...(graph.edges||[]).map(e=>({data:e}))];cy=cytoscape({container:$('architecture-graph'),elements,style:graphStyle(),layout:{name:networkLayout?'cose':'breadthfirst',directed:true,animate:false,padding:40,spacingFactor:1.3},minZoom:.1,maxZoom:3,wheelSensitivity:.2});cy.on('tap','node',event=>inspectComponent(event.target.id()));cy.on('tap','edge',event=>{const e=event.target.data();$('component-inspector').innerHTML=`<div class="eyebrow">RELATIONSHIP</div><h3>${esc(e.label)}</h3><p>${esc(e.basis)}</p><button class="source-button" data-source="${esc(e.path)}" data-line="${e.line}">${esc(e.path)}:${e.line}</button>`;sourceButtons($('component-inspector'))});$('component-list').innerHTML=(graph.nodes||[]).map(n=>`<div class="component-row"><span>${esc(n.kind)}</span><button class="source-button" data-component="${esc(n.id)}">${esc(n.label)}</button><span>${esc(n.path||'')}</span></div>`).join('')||'<p class="muted">Architecture extraction has not finished.</p>';$('component-list').querySelectorAll('[data-component]').forEach(b=>b.onclick=()=>inspectComponent(b.dataset.component));filterGraph()}
function inspectComponent(id){const graph=current.architecture;const node=graph.nodes.find(n=>n.id===id);if(!node)return;const edges=graph.edges.filter(e=>e.source===id||e.target===id);const label=key=>graph.nodes.find(n=>n.id===key)?.label||key;$('component-inspector').innerHTML=`<div class="eyebrow">${esc(node.kind)}</div><h3>${esc(node.label)}</h3><p>${esc(node.detail||'Observed in repository source.')}</p>${node.path?`<button class="source-button" data-source="${esc(node.path)}" data-line="${node.line}">${esc(node.path)}:${node.line}</button>`:''}<h3>Relationships <small>${edges.length}</small></h3><ul>${edges.slice(0,30).map(e=>`<li>${esc(label(e.source))} → ${esc(e.label)} → ${esc(label(e.target))}</li>`).join('')}</ul>`;sourceButtons($('component-inspector'));if(cy){cy.elements().unselect();cy.getElementById(id).select()}}
function filterGraph(){if(!cy)return;const query=$('graph-search').value.toLowerCase(),kind=$('graph-filter').value;cy.elements().removeClass('faded highlight');if(!query&&kind==='all')return;cy.elements().addClass('faded');cy.nodes().forEach(n=>{if((!query||`${n.data('label')} ${n.data('detail')||''}`.toLowerCase().includes(query))&&(kind==='all'||n.data('kind')===kind)){n.removeClass('faded').addClass('highlight');n.connectedEdges().removeClass('faded')}})}
function drawExperiments(){if(!current||tab!=='experiments'||view!=='workspace')return;const rows=current.experiments||[];const key=current.id+JSON.stringify(rows.map(x=>[x.id,x.status]));if(experimentKey!==key||!experimentCy){experimentKey=key;if(experimentCy)experimentCy.destroy();const nodes=rows.map((x,i)=>({data:{id:x.id,label:x.title+'\n'+x.status,color:['passed','accepted','supported','improved'].includes(x.status.toLowerCase())?'#729778':['failed','rejected','not_supported'].includes(x.status.toLowerCase())?'#b77872':x.status==='running'?'#6f87b4':'#b5a174'},position:{x:i*195,y:80}}));const edges=rows.slice(1).map((x,i)=>({data:{id:'flow-'+x.id,source:x.parent||rows[i].id,target:x.id,label:x.kind==='candidate'?'candidate':'then'}}));experimentCy=cytoscape({container:$('experiment-graph'),elements:[...nodes,...edges],style:graphStyle(),layout:{name:'preset',fit:true,padding:35},minZoom:.12,maxZoom:3,wheelSensitivity:.2});experimentCy.on('tap','node',event=>selectExperiment(event.target.id()))}else experimentCy.resize();$('experiment-list').innerHTML=rows.map(x=>`<button class="experiment-item ${x.id===selectedExperiment?'selected':''}" data-exp="${esc(x.id)}">${badge(x.status)}<small>${esc(x.id)} · ${esc(x.kind)}</small><strong>${esc(x.title)}</strong><small>${Number(x.duration_seconds||0).toFixed(1)}s</small></button>`).join('')||'<p class="muted">Experiments will appear as the investigation proceeds.</p>';$('experiment-list').querySelectorAll('[data-exp]').forEach(b=>b.onclick=()=>selectExperiment(b.dataset.exp));if(!selectedExperiment&&rows.length)selectedExperiment=rows.at(-1).id;if(selectedExperiment)renderExperiment()}
function selectExperiment(id){selectedExperiment=id;renderExperiment();$('experiment-list').querySelectorAll('[data-exp]').forEach(b=>b.classList.toggle('selected',b.dataset.exp===id));if(experimentCy){experimentCy.elements().unselect();experimentCy.getElementById(id).select()}}
function renderExperiment(){const x=current.experiments.find(e=>e.id===selectedExperiment);if(!x)return;const section=(title,text,open=false)=>text?`<details ${open?'open':''}><summary>${esc(title)}</summary><pre>${esc(text)}</pre></details>`:'';$('experiment-detail').innerHTML=`<div class="section-heading"><div><div class="eyebrow">${esc(x.id)} · ${esc(x.kind)}</div><h2>${esc(x.title)}</h2></div>${badge(x.status)}</div><p>${esc(x.conclusion||(x.status==='running'?'Running…':'Candidate evaluated; inspect its result and evidence below.'))}</p><p class="muted">${esc(time(x.started))} · ${Number(x.duration_seconds||x.metrics?.duration_seconds||0).toFixed(2)} seconds${current.reused_from?' · original reused evidence':''}</p>${section('Input and rationale',x.input)}${section('Model response',x.model_response)}${section('Exact command',x.command?.join(' '))}${section('Standard output',x.stdout,true)}${section('Errors / blocked checks',x.stderr,true)}${section('Proposed patch',x.patch,true)}${x.metrics?'<h3>Benchmark samples</h3><select id="metric-selector" aria-label="Benchmark metric"><option value="bytes_op">Bytes per operation</option><option value="ns_op">Nanoseconds per operation</option><option value="allocs_op">Allocations per operation</option></select><div id="metric-chart"></div>':''}${x.evidence?.length?section('Source evidence',x.evidence.join('\n')):''}`;if(x.metrics){$('metric-selector').onchange=()=>renderMetrics(x.metrics);renderMetrics(x.metrics)}}
function renderMetrics(m){if(!m.samples?.length){$('metric-chart').textContent='No benchmark samples collected. This candidate did not reach successful measurement.';return}const experiment=current.experiments.find(x=>x.id===selectedExperiment),baseline=current.experiments.find(x=>x.id===experiment?.parent)?.metrics;const metric=$('metric-selector').value,samples=m.samples||[],max=Math.max(...samples.map(s=>s[metric]),1);$('metric-chart').innerHTML=`${baseline?`<p>Baseline median: <strong>${Number(baseline[metric]).toLocaleString()}</strong> → Candidate median: <strong>${Number(m[metric]).toLocaleString()}</strong> · ${(100*(baseline[metric]-m[metric])/baseline[metric]).toFixed(2)}% reduction</p>`:''}<div class="metric-bars">${samples.map((s,i)=>`<div class="metric-column" style="height:${Math.max(3,100*s[metric]/max)}%"><small>${Number(s[metric]).toLocaleString()}</small><span>Sample ${i+1}</span></div>`).join('')}</div><p class="muted">Median: ${Number(m[metric]||0).toLocaleString()} · Tests ${m.tests_passed?'passed':'not confirmed'}</p>`}
async function showSource(path,line){if(!current)return;try{const source=await api('/api/investigations/'+encodeURIComponent(current.id)+'/source?path='+encodeURIComponent(path));$('source-title').textContent=`${path}:${line} · ${short(source.revision)}`;$('source-content').textContent=source.content.split('\n').map((s,i)=>`${i+1===line?'→':' '} ${String(i+1).padStart(4)}  ${s}`).join('\n');$('source-dialog').showModal();$('source-content').scrollTop=Math.max(0,(line-4)*18)}catch(error){toast(error.message)}}
async function submit(request){busy=true;renderSidebar();try{const result=await api('/api/investigations',{method:'POST',body:JSON.stringify(request)});await refresh();await selectRun(result.id)}catch(error){toast(error.message)}finally{busy=false;renderSidebar()}}
$('investigation-form').addEventListener('submit',event=>{event.preventDefault();submit({url:$('repo-url').value.trim(),objective:$('objective').value.trim(),ref:$('repo-ref').value.trim(),runtime:$('runtime-checks').checked,model:$('model-review').checked,optimize:$('optimize').checked,benchmark:$('benchmark').value.trim(),module:$('go-module').value.trim(),force:false})});
initAgents();$('new-investigation').onclick=newInvestigation;$('library-button').onclick=()=>{location.hash='library';switchView('library')};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('rerun-button').onclick=()=>{if(current)submit({...current.request,force:true})};$('cancel-button').onclick=async()=>{try{await api('/api/investigations/cancel',{method:'POST',body:'{}'});toast('Stopping the investigation; completed evidence will be retained.')}catch(e){toast(e.message)}};
$('graph-search').oninput=filterGraph;$('graph-filter').onchange=filterGraph;$('graph-fit').onclick=()=>cy?.fit(undefined,35);$('graph-layout').onclick=()=>{networkLayout=!networkLayout;graphKey='';drawArchitecture()};$('experiment-fit').onclick=()=>experimentCy?.fit(undefined,35);$('graph-export').onclick=()=>{if(!cy)return;const a=document.createElement('a');a.href=cy.png({bg:'#fbfcfa',full:true,scale:2,maxWidth:6000,maxHeight:6000});a.download='veda-architecture.png';a.click()};$('close-source').onclick=()=>$('source-dialog').close();$('close-health').onclick=()=>$('health-dialog').close();$('health-button').onclick=async()=>{$('health-dialog').showModal();$('health-content').textContent='Checking local services…';try{const h=await api('/api/health');$('health-content').innerHTML=`<dl><dt>Local model</dt><dd>${h.model_ready?'Ready':esc(h.model_error||'Not ready')}</dd><dt>Docker</dt><dd>${h.docker?'Ready':esc(h.docker_error||'Not ready')}</dd><dt>Configured model</dt><dd>${esc(h.model)}</dd><dt>Shared knowledge</dt><dd>${esc(library.knowledge_dir)}</dd></dl>`}catch(e){$('health-content').textContent=e.message}};
async function refresh(){if(refreshing)return;refreshing=true;try{library=await api('/api/library');setAgentConnection(true);renderSidebar();if(view==='agents')renderAgentDashboard();if(view==='library')renderLibrary();if(selected&&view==='workspace'){const id=selected;const run=await api('/api/investigations/'+encodeURIComponent(id));if(selected===id&&JSON.stringify(current)!==JSON.stringify(run)){current=run;renderRun()}}}catch(e){setAgentConnection(false);$('connection-status').textContent='Connection unavailable';if(!library.token)toast(e.message)}finally{refreshing=false}}
async function routeHash(){let id='';try{id=decodeURIComponent(location.hash.slice(1))}catch{}if(id&&/^RUN-/.test(id)){if(selected!==id||view!=='workspace')await selectRun(id)}else switchView(id==='new'?'composer':id==='library'?'library':'agents')}
window.addEventListener('hashchange',routeHash);
(async()=>{await refresh();await routeHash();setInterval(refresh,2500)})();
